swagger: "2.0"
info:
  title: API
  description: API Aplicacion Voto - Entidades Core
  version: 1.0.0
  termsOfService: http://oas.udistrital.edu.co/
  contact:
    email: ssierraf@correo.udistrital.edu.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /arbol_rubro/:
    get:
      tags:
      - arbol_rubro
      description: get all objects
      operationId: ArbolRubrosController.GetAll
      responses:
        "200":
          description: ArbolRubros models.ArbolRubros
        "403":
          description: :objectId is empty
    post:
      tags:
      - arbol_rubro
      description: Crear ArbolRubros
      operationId: ArbolRubrosController.Crear ArbolRubros
      parameters:
      - in: body
        name: body
        description: Body para la creacion de ArbolRubros
        required: true
        schema:
          $ref: '#/definitions/models.ArbolRubros'
      responses:
        "200":
          description: '{int} ArbolRubros.Id'
        "403":
          description: body is empty
    options:
      tags:
      - arbol_rubro
      description: Crear ArbolRubros
      operationId: ArbolRubrosController.Preflight options
      parameters:
      - in: body
        name: body
        description: Body para la creacion de ArbolRubros
        required: true
        schema:
          $ref: '#/definitions/models.ArbolRubros'
      responses:
        "200":
          description: '{int} ArbolRubros.Id'
        "403":
          description: body is empty
  /arbol_rubro/{id}:
    get:
      tags:
      - arbol_rubro
      description: get ArbolRubros by nombre
      operationId: ArbolRubrosController.Get
      parameters:
      - in: path
        name: nombre
        description: El nombre de la ArbolRubros a consultar
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ArbolRubros'
        "403":
          description: :uid is empty
  /arbol_rubro/{objectId}:
    put:
      tags:
      - arbol_rubro
      description: update the ArbolRubros
      operationId: ArbolRubrosController.Update
      parameters:
      - in: path
        name: objectId
        description: The objectid you want to update
        required: true
        type: string
      - in: body
        name: body
        description: The body
        required: true
        schema:
          $ref: '#/definitions/models.Object'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "403":
          description: :objectId is empty
    delete:
      tags:
      - arbol_rubro
      description: Borrar ArbolRubros
      operationId: ArbolRubrosController.Borrar ArbolRubros
      parameters:
      - in: path
        name: objectId
        description: El ObjectId del objeto que se quiere borrar
        required: true
        type: string
      responses:
        "200":
          description: '{string} ok'
        "403":
          description: objectId is empty
    options:
      tags:
      - arbol_rubro
      description: Crear ArbolRubros
      operationId: ArbolRubrosController.Preflight options
      parameters:
      - in: body
        name: body
        description: Body para la creacion de ArbolRubros
        required: true
        schema:
          $ref: '#/definitions/models.ArbolRubros'
      responses:
        "200":
          description: '{int} ArbolRubros.Id'
        "403":
          description: body is empty
  /arbol_rubro/ArbolRubro/{raiz}/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro
      description: Construye el árbol a un nivel dependiendo de la raíz
      operationId: ArbolRubrosController.Preflight options
      parameters:
      - in: body
        name: body
        description: Código de la raíz
        schema:
          $ref: '#/definitions/stringtrue'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "404":
          description: body is empty
  /arbol_rubro/FullArbolRubro/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro
      description: Construye el árbol a un nivel dependiendo de la raíz
      operationId: ArbolRubrosController.FullArbolRubro
      parameters:
      - in: body
        name: body
        description: Código de la raíz
        schema:
          $ref: '#/definitions/stringtrue'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "404":
          description: body is empty
  /arbol_rubro/RaicesArbol/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro
      description: RaicesArbol
      operationId: ArbolRubrosController.RaicesArbol
      parameters:
      - in: body
        name: body
        description: Body para la creacion de Rubro
        required: true
        schema:
          $ref: '#/definitions/models.Rubro'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "404":
          description: body is empty
  /arbol_rubro/eliminarRubro/{idPsql}:
    delete:
      tags:
      - arbol_rubro
      description: recibe el idPsql del rubro desde api mid para eliminar el rubro
      operationId: ArbolRubrosController.Eliminar rubro
      parameters:
      - in: interface{}
        name: body
        description: Body para la eliminación de un rubro
        schema:
          $ref: '#/definitions/true'
      responses:
        "201":
          description: '{string} sucess'
        "403":
          description: body is empty
  /arbol_rubro/registrarRubro:
    post:
      tags:
      - arbol_rubro
      description: Convierte la estructura del api mid para registrarla en un documento
        mongo
      operationId: ArbolRubrosController.Registra rubro
      parameters:
      - in: interface{}
        name: body
        description: Body para la creacion de un nuevo rubro
        schema:
          $ref: '#/definitions/true'
      responses:
        "201":
          description: '{string} recibido'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/:
    options:
      tags:
      - arbol_rubro_apropiaciones
      description: Crear ArbolRubroApropiacion2018
      operationId: ArbolRubroApropiacionController.Preflight options
      parameters:
      - in: body
        name: body
        description: Body para la creacion de ArbolRubroApropiacion2018
        required: true
        schema:
          $ref: '#/definitions/models.ArbolRubroApropiacion2018'
      responses:
        "200":
          description: '{int} ArbolRubroApropiacion2018.Id'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/{id}/{vigencia}/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: get ArbolRubroApropiacion2018 by nombre
      operationId: ArbolRubroApropiacionController.Get
      parameters:
      - in: path
        name: nombre
        description: El nombre de la ArbolRubroApropiacion2018 a consultar
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.ArbolRubroApropiacion2018'
        "403":
          description: :uid is empty
  /arbol_rubro_apropiaciones/{objectId}:
    delete:
      tags:
      - arbol_rubro_apropiaciones
      description: Borrar ArbolRubroApropiacion2018
      operationId: ArbolRubroApropiacionController.Delete ArbolRubroApropiacion2018
      parameters:
      - in: path
        name: objectId
        description: El ObjectId del objeto que se quiere borrar
        required: true
        type: string
      responses:
        "200":
          description: '{string} ok'
        "403":
          description: objectId is empty
    options:
      tags:
      - arbol_rubro_apropiaciones
      description: Crear ArbolRubroApropiacion2018
      operationId: ArbolRubroApropiacionController.Preflight options
      parameters:
      - in: body
        name: body
        description: Body para la creacion de ArbolRubroApropiacion2018
        required: true
        schema:
          $ref: '#/definitions/models.ArbolRubroApropiacion2018'
      responses:
        "200":
          description: '{int} ArbolRubroApropiacion2018.Id'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/{objectId}/{vigencia}/{unidadEjecutora}:
    put:
      tags:
      - arbol_rubro_apropiaciones
      description: update the ArbolRubroApropiacion2018
      operationId: ArbolRubroApropiacionController.Update
      parameters:
      - in: path
        name: objectId
        description: The objectid you want to update
        required: true
        type: string
      - in: body
        name: body
        description: The body
        required: true
        schema:
          $ref: '#/definitions/models.Object'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "403":
          description: :objectId is empty
  /arbol_rubro_apropiaciones/{vigencia}/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: get all objects
      operationId: ArbolRubroApropiacionController.GetAll
      responses:
        "200":
          description: ArbolRubroApropiacion models.ArbolRubroApropiacion
        "403":
          description: :objectId is empty
    post:
      tags:
      - arbol_rubro_apropiaciones
      description: Crear ArbolRubroApropiacion2018
      operationId: ArbolRubroApropiacionController.Crear ArbolRubroApropiacion2018
      parameters:
      - in: body
        name: body
        description: Body para la creacion de ArbolRubroApropiacion2018
        required: true
        schema:
          $ref: '#/definitions/models.ArbolRubroApropiacion2018'
      responses:
        "200":
          description: '{int} ArbolRubroApropiacion2018.Id'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/ArbolApropiacion/{raiz}/{unidadEjecutora}/{vigencia}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: Devuelve un nivel del árbol de apropiaciones
      operationId: ArbolRubroApropiacionController.Preflight ArbolApropiacion
      parameters:
      - in: body
        name: body
        description: Body para la creacion de ArbolRubroApropiacion2018
        required: true
        schema:
          $ref: '#/definitions/models.ArbolRubroApropiacion2018'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/RaicesArbolApropiacion/{unidadEjecutora}/{vigencia}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: RaicesArbolApropiacion
      operationId: ArbolRubroApropiacionController.RaicesArbolApropiacion
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "404":
          description: body is empty
  /arbol_rubro_apropiaciones/SaldoApropiacion/{rubro}/{unidadEjecutora}/{vigencia}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: Devuelve el saldo de una apropiación especifica
      operationId: ArbolRubroApropiacionController.SaldoApropiacion
      parameters:
      - in: body
        name: body
        description: json de movimientos enviado desde el api_mid_financiera
        required: true
        schema:
          $ref: '#/definitions/models.Object'
      responses:
        "200":
          description: '{string} success'
        "403":
          description: error
  /arbol_rubro_apropiaciones/SaldoMovimiento/{idPsql}/{rubro}/{tipoMovimiento}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: Devuelve el saldo de un CDP especifico
      operationId: ArbolRubroApropiacionController.SaldoMovimiento
      parameters:
      - in: path
        name: idPsql
        description: idPsql del documento
        required: true
        type: integer
        format: int64
      - in: path
        name: rubro
        description: código del rubro
        required: true
        type: string
      - in: query
        name: fuente
        description: fuente de financiamiento
        type: string
      responses:
        "200":
          description: '{string} success'
        "403":
          description: error
  /arbol_rubro_apropiacionesRegistrarApropiacionInicial/{vigencia}:
    post:
      tags:
      - arbol_rubro_apropiaciones
      description: Crear ArbolRubroApropiacion2018
      operationId: ArbolRubroApropiacionController.RegistrarApropiacionInicial...
      parameters:
      - in: body
        name: body
        description: Body para la creacion de ApropiacionInicial
        required: true
        schema:
          $ref: '#/definitions/models.ArbolRubroApropiacion2018'
      responses:
        "200":
          description: '{int} ArbolRubroApropiacion2018.Id'
        "403":
          description: body is empty
  /fuente_financiamiento/:
    post:
      tags:
      - fuente_financiamiento
      description: create FuenteFinanciamiento
      operationId: FuenteFinanciamientoController.Create
      parameters:
      - in: body
        name: body
        description: body for FuenteFinanciamiento content
        required: true
        schema:
          $ref: '#/definitions/models.FuenteFinanciamiento'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.FuenteFinanciamiento'
        "403":
          description: body is empty
  /fuente_financiamiento/{id}:
    get:
      tags:
      - fuente_financiamiento
      description: get FuenteFinanciamiento by id
      operationId: FuenteFinanciamientoController.GetOne
      parameters:
      - in: path
        name: id
        description: The key for staticblock
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.FuenteFinanciamiento'
        "403":
          description: :id is empty
  /movimientosRegistrarMovimiento/{tipoPago}:
    post:
      tags:
      - movimientos
      description: Registra los movimientos (como cdp, rp, ver variable tipoMovimiento)
        y los propaga tanto en la colección
      operationId: MovimientosController.RegistrarMovimiento
      parameters:
      - in: body
        name: body
        description: json de movimientos enviado desde el api_mid_financiera
        required: true
        schema:
          $ref: '#/definitions/models.Object'
      responses:
        "200":
          description: '{string} success'
        "403":
          description: error
definitions:
  1296.0xc0003ab170.false:
    title: "false"
    type: object
  models.ArbolRubroApropiacion2018:
    title: ArbolRubroApropiacion2018
    type: object
  models.ArbolRubros:
    title: ArbolRubros
    type: object
    properties:
      _id:
        type: string
      Descripcion:
        type: string
      Hijos:
        type: array
        items:
          type: string
      Id:
        type: string
      Nombre:
        type: string
      Padre:
        type: string
      UnidadEjecutora:
        type: string
  models.FuenteFinanciamiento:
    title: FuenteFinanciamiento
    type: object
    properties:
      _id:
        type: string
      descripcion:
        type: string
      idpsql:
        type: integer
        format: int64
      nombre:
        type: string
      tipo_fuente:
        $ref: '#/definitions/1296.0xc0003ab170.false'
      unidad_ejecutora:
        type: integer
        format: int64
      valor_acumulado:
        type: number
        format: double
      valor_original:
        type: number
        format: double
  models.Object:
    title: Object
    type: object
  models.Rubro:
    title: Rubro
    type: object
  stringtrue:
    title: stringtrue
    type: object
  "true":
    title: "true"
    type: object
tags:
- name: arbol_rubro
  description: |
    ArbolRubrosController estructura para un controlador de beego
- name: arbol_rubro_apropiaciones
  description: |
    ArbolRubroApropiacionController struct del controlador, utiliza los atributos y funciones de un controlador de beego
- name: fuente_financiamiento
  description: |
    FuenteFinanciamientoController operations for FuenteFinanciamiento
- name: movimientos
  description: |
    MovimientosController estructura para un controlador de beego
