swagger: "2.0"
info:
  title: API
  description: API Aplicacion Voto - Entidades Core
  version: 1.0.0
  termsOfService: http://oas.udistrital.edu.co/
  contact:
    email: ssierraf@correo.udistrital.edu.co
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /arbol_rubro/:
    get:
      tags:
      - arbol_rubro
      description: get all objects
      operationId: NodoRubroController.GetAll
      responses:
        "200":
          description: NodoRubro models.NodoRubro
        "403":
          description: :objectId is empty
    post:
      tags:
      - arbol_rubro
      description: Crear NodoRubro
      operationId: NodoRubroController.Crear NodoRubro
      parameters:
      - in: body
        name: body
        description: Body para la creacion de NodoRubro
        required: true
        schema:
          $ref: '#/definitions/models.NodoRubro'
      responses:
        "200":
          description: '{int} NodoRubro.Id'
        "403":
          description: body is empty
    options:
      tags:
      - arbol_rubro
      description: Crear NodoRubro
      operationId: NodoRubroController.Preflight options
      parameters:
      - in: body
        name: body
        description: Body para la creacion de NodoRubro
        required: true
        schema:
          $ref: '#/definitions/models.NodoRubro'
      responses:
        "200":
          description: '{int} NodoRubro.Id'
        "403":
          description: body is empty
  /arbol_rubro/{id}:
    get:
      tags:
      - arbol_rubro
      description: get NodoRubro by nombre
      operationId: NodoRubroController.Get
      parameters:
      - in: path
        name: nombre
        description: El nombre de la NodoRubro a consultar
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.NodoRubro'
        "403":
          description: :uid is empty
  /arbol_rubro/{objectId}:
    put:
      tags:
      - arbol_rubro
      description: update the NodoRubro
      operationId: NodoRubroController.Update
      parameters:
      - in: path
        name: objectId
        description: The objectid you want to update
        required: true
        type: string
      - in: body
        name: body
        description: The body
        required: true
        schema:
          $ref: '#/definitions/models.Object'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "403":
          description: :objectId is empty
    delete:
      tags:
      - arbol_rubro
      description: Borrar NodoRubro
      operationId: NodoRubroController.Borrar NodoRubro
      parameters:
      - in: path
        name: objectId
        description: El ObjectId del objeto que se quiere borrar
        required: true
        type: string
      responses:
        "200":
          description: '{string} ok'
        "403":
          description: objectId is empty
    options:
      tags:
      - arbol_rubro
      description: Crear NodoRubro
      operationId: NodoRubroController.Preflight options
      parameters:
      - in: body
        name: body
        description: Body para la creacion de NodoRubro
        required: true
        schema:
          $ref: '#/definitions/models.NodoRubro'
      responses:
        "200":
          description: '{int} NodoRubro.Id'
        "403":
          description: body is empty
  /arbol_rubro/ArbolRubro/{raiz}/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro
      description: Construye el árbol a un nivel dependiendo de la raíz
      operationId: NodoRubroController.Preflight options
      parameters:
      - in: body
        name: body
        description: Código de la raíz
        schema:
          $ref: '#/definitions/stringtrue'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "404":
          description: body is empty
  /arbol_rubro/FullArbolRubro/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro
      description: Construye el árbol a un nivel dependiendo de la raíz
      operationId: NodoRubroController.FullArbolRubro
      parameters:
      - in: body
        name: body
        description: Código de la raíz
        schema:
          $ref: '#/definitions/stringtrue'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "404":
          description: body is empty
  /arbol_rubro/RaicesArbol/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro
      description: RaicesArbol
      operationId: NodoRubroController.RaicesArbol
      parameters:
      - in: body
        name: body
        description: Body para la creacion de Rubro
        required: true
        schema:
          $ref: '#/definitions/models.Rubro'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "404":
          description: body is empty
  /arbol_rubro/eliminarRubro/{idPsql}:
    delete:
      tags:
      - arbol_rubro
      description: recibe el idPsql del rubro desde api mid para eliminar el rubro
      operationId: NodoRubroController.Eliminar rubro
      parameters:
      - in: interface{}
        name: body
        description: Body para la eliminación de un rubro
        schema:
          $ref: '#/definitions/true'
      responses:
        "201":
          description: '{string} sucess'
        "403":
          description: body is empty
  /arbol_rubro/registrarRubro:
    post:
      tags:
      - arbol_rubro
      description: Convierte la estructura del api mid para registrarla en un documento
        mongo
      operationId: NodoRubroController.Registra rubro
      parameters:
      - in: interface{}
        name: body
        description: Body para la creacion de un nuevo rubro
        schema:
          $ref: '#/definitions/true'
      responses:
        "201":
          description: '{string} recibido'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/:
    options:
      tags:
      - arbol_rubro_apropiaciones
      description: Crear NodoRubroApropiacion2018
      operationId: NodoRubroApropiacionController.Preflight options
      parameters:
      - in: body
        name: body
        description: Body para la creacion de NodoRubroApropiacion2018
        required: true
        schema:
          $ref: '#/definitions/models.NodoRubroApropiacion2018'
      responses:
        "200":
          description: '{int} NodoRubroApropiacion2018.Id'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/{id}/{vigencia}/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: get NodoRubroApropiacion2018 by nombre
      operationId: NodoRubroApropiacionController.Get
      parameters:
      - in: path
        name: nombre
        description: El nombre de la NodoRubroApropiacion2018 a consultar
        required: true
        type: string
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.NodoRubroApropiacion2018'
        "403":
          description: :uid is empty
  /arbol_rubro_apropiaciones/{objectId}:
    delete:
      tags:
      - arbol_rubro_apropiaciones
      description: Borrar NodoRubroApropiacion2018
      operationId: NodoRubroApropiacionController.Delete NodoRubroApropiacion2018
      parameters:
      - in: path
        name: objectId
        description: El ObjectId del objeto que se quiere borrar
        required: true
        type: string
      responses:
        "200":
          description: '{string} ok'
        "403":
          description: objectId is empty
    options:
      tags:
      - arbol_rubro_apropiaciones
      description: Crear NodoRubroApropiacion2018
      operationId: NodoRubroApropiacionController.Preflight options
      parameters:
      - in: body
        name: body
        description: Body para la creacion de NodoRubroApropiacion2018
        required: true
        schema:
          $ref: '#/definitions/models.NodoRubroApropiacion2018'
      responses:
        "200":
          description: '{int} NodoRubroApropiacion2018.Id'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/{objectId}/{vigencia}/{unidadEjecutora}:
    put:
      tags:
      - arbol_rubro_apropiaciones
      description: update the NodoRubroApropiacion2018
      operationId: NodoRubroApropiacionController.Update
      parameters:
      - in: path
        name: objectId
        description: The objectid you want to update
        required: true
        type: string
      - in: body
        name: body
        description: The body
        required: true
        schema:
          $ref: '#/definitions/models.Object'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "403":
          description: :objectId is empty
  /arbol_rubro_apropiaciones/{vigencia}/{unidadEjecutora}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: get all objects
      operationId: NodoRubroApropiacionController.GetAll
      responses:
        "200":
          description: NodoRubroApropiacion models.NodoRubroApropiacion
        "403":
          description: :objectId is empty
    post:
      tags:
      - arbol_rubro_apropiaciones
      description: Crear NodoRubroApropiacion2018
      operationId: NodoRubroApropiacionController.Crear NodoRubroApropiacion2018
      parameters:
      - in: body
        name: body
        description: Body para la creacion de NodoRubroApropiacion2018
        required: true
        schema:
          $ref: '#/definitions/models.NodoRubroApropiacion2018'
      responses:
        "200":
          description: '{int} NodoRubroApropiacion2018.Id'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/ArbolApropiacion/{raiz}/{unidadEjecutora}/{vigencia}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: Devuelve un nivel del árbol de apropiaciones
      operationId: NodoRubroApropiacionController.Preflight ArbolApropiacion
      parameters:
      - in: body
        name: body
        description: Body para la creacion de NodoRubroApropiacion2018
        required: true
        schema:
          $ref: '#/definitions/models.NodoRubroApropiacion2018'
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "403":
          description: body is empty
  /arbol_rubro_apropiaciones/RaicesArbolApropiacion/{unidadEjecutora}/{vigencia}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: RaicesArbolApropiacion
      operationId: NodoRubroApropiacionController.RaicesArbolApropiacion
      responses:
        "200":
          description: ""
          schema:
            $ref: '#/definitions/models.Object'
        "404":
          description: body is empty
  /arbol_rubro_apropiaciones/SaldoApropiacion/{rubro}/{unidadEjecutora}/{vigencia}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: Devuelve el saldo de una apropiación especifica
      operationId: NodoRubroApropiacionController.SaldoApropiacion
      parameters:
      - in: body
        name: body
        description: json de movimientos enviado desde el api_mid_financiera
        required: true
        schema:
          $ref: '#/definitions/models.Object'
      responses:
        "200":
          description: '{string} success'
        "403":
          description: error
  /arbol_rubro_apropiaciones/SaldoMovimiento/{idPsql}/{rubro}/{tipoMovimiento}:
    get:
      tags:
      - arbol_rubro_apropiaciones
      description: Devuelve el saldo de un CDP especifico
      operationId: NodoRubroApropiacionController.SaldoMovimiento
      parameters:
      - in: path
        name: idPsql
        description: idPsql del documento
        required: true
        type: integer
        format: int64
      - in: path
        name: rubro
        description: código del rubro
        required: true
        type: string
      - in: query
        name: fuente
        description: fuente de financiamiento
        type: string
      responses:
        "200":
          description: '{string} success'
        "403":
          description: error
  /arbol_rubro_apropiacionesRegistrarApropiacionInicial/{vigencia}:
    post:
      tags:
      - arbol_rubro_apropiaciones
      description: Crear NodoRubroApropiacion2018
      operationId: NodoRubroApropiacionController.RegistrarApropiacionInicial...
      parameters:
      - in: body
        name: body
        description: Body para la creacion de ApropiacionInicial
        required: true
        schema:
          $ref: '#/definitions/models.NodoRubroApropiacion2018'
      responses:
        "200":
          description: '{int} NodoRubroApropiacion2018.Id'
        "403":
          description: body is empty
  /arbol_rubro_apropiacionesRegistrarMovimiento/{tipoPago}:
    post:
      tags:
      - arbol_rubro_apropiaciones
      description: Registra los movimientos (como cdp, rp, ver variable tipoMovimiento)
        y los propaga tanto en la colección
      operationId: NodoRubroApropiacionController.RegistrarMovimiento
      parameters:
      - in: body
        name: body
        description: json de movimientos enviado desde el api_mid_financiera
        required: true
        schema:
          $ref: '#/definitions/models.Object'
      responses:
        "200":
          description: '{string} success'
        "403":
          description: error
  /fuente_financiamiento/:
    post:
      tags:
      - fuente_financiamiento
      description: create FuenteFinanciamiento
      operationId: FuenteFinanciamientoController.Create
      parameters:
      - in: body
        name: body
        description: body for FuenteFinanciamiento content
        required: true
        schema:
          $ref: '#/definitions/models.FuenteFinanciamiento'
      responses:
        "201":
          description: ""
          schema:
            $ref: '#/definitions/models.FuenteFinanciamiento'
        "403":
          description: body is empty
definitions:
  10312.0xc00044f0e0.false:
    title: "false"
    type: object
  12677.string.float64:
    title: float64
    type: object
  models.FuenteFinanciamiento:
    title: FuenteFinanciamiento
    type: object
    properties:
      Rubros:
        $ref: '#/definitions/map[string][10470.0xc00044f110.false]'
      TipoFuente:
        $ref: '#/definitions/10312.0xc00044f0e0.false'
      ValorOriginal:
        type: number
        format: double
  models.General:
    title: General
    type: object
    properties:
      _id:
        type: string
      Descripcion:
        type: string
      IdPsql:
        type: integer
        format: int64
      Movimientos:
        $ref: '#/definitions/12677.string.float64'
      Nombre:
        type: string
      Vigencia:
        type: integer
        format: int64
  models.NodoRubro:
    title: NodoRubro
    type: object
    properties:
      Hijos:
        type: array
        items:
          type: string
      Padre:
        type: string
      UnidadEjecutora:
        type: string
  models.NodoRubroApropiacion2018:
    title: NodoRubroApropiacion2018
    type: object
  models.Object:
    title: Object
    type: object
  models.Rubro:
    title: Rubro
    type: object
  stringtrue:
    title: stringtrue
    type: object
  "true":
    title: "true"
    type: object
tags:
- name: arbol_rubro
  description: |
    NodoRubroController estructura para un controlador de beego
- name: arbol_rubro_apropiaciones
  description: |
    NodoRubroApropiacionController struct del controlador, utiliza los atributos y funciones de un controlador de beego
- name: fuente_financiamiento
  description: |
    FuenteFinanciamientoController operations for FuenteFinanciamiento
